### ISSUE TITLE
demo-store command should ask to confirm seeding

### ISSUE THREAD

**Issue by robbieaverill** [chec/cli#28]
If I were to set up multiple demo stores, I wouldn't necessarily want to have multiple sets of products seeded. If it were to ask to confirm whether I wanted this I could say no before it does this.

**Comment by ScopeyNZ** [comment]
Agreed. It would be nice to add a `--skip-seed` flag too.

**Comment by robbieaverill** [comment]
Yeah for sure - I think we should aim for every prompted option to be controllable with a flag too, in cases where people want to use it with no interaction

**Comment by robbieaverill** [comment]
@ricardodesimas also suggested that we could check for an existing product/category/etc before seeding to prevent double ups, which could also be an optional argument

**Comment by rafaeelaudibert** [comment]
Hey, I can definitely take a look at this! What are we going for now? (as there are some different ideas on the PR). What do you think about making this issue related to asking this new question during the creation?

We could create a different issue (and make it available through Hacktoberfest as well), to make the `--skip-*` flags

**Comment by robbieaverill** [comment]
Hey @rafaeelaudibert, that's a good idea, but I don't think having a separate issue would be useful here. The approach for this issue should be to ask to confirm whether you want to seed sample data, and the skip seed flag @ScopeyNZ suggested would take priority meaning we would not ask to confirm seeding because we know the answer is "no". Hope this is helpful!

**Comment by rafaeelaudibert** [comment]
Perfect, can go the way you suggested! Could you please assign this to me? Will probably have this sorted next week.

**Comment by robbieaverill** [comment]
Sure, thanks for contributing!

**Comment by hashtag-incIude** [comment]
add --skip-seed flag

**Comment by robbieaverill** [comment]
Thank you for your work on this @rafaeelaudibert

**Comment by hashtag-incIude** [comment]
Sir i am eligible for getting the swag.
If yes how can I get it ..

**Comment by ScopeyNZ** [comment]
Hi @hashtag-incIude. You have to make a pull request and have it merged for you to be eligible for swag. I can't see that you've raised any pull requests against any of our repos so unfortunately you're not eligible 😢

**Comment by hashtag-incIude** [comment]
Sir i have it now,can you please check it once.

**Comment by hashtag-incIude** [comment]
Sir I have done it now,can you please check it once.

**Comment by ScopeyNZ** [comment]
Hi @hashtag-incIude. Sorry, I can't find any pull request from you on any of our hacktoberfest repos. A comment on an issue isn't the kind of contribution we distribute swag for. If you make a **pull request** that is accepted and merged, then you can be eligible. Thanks for your interest!
