### ISSUE TITLE
Add `whoami` command

### ISSUE THREAD

**Issue by robbieaverill** [chec/cli#4]
Example use:

```
$ chec whoami
```

Example response:

```
robbie@chec.io - My demo store
```

**Comment by john-raymon** [comment]
Why not.

**Comment by dvnkshl** [comment]
This is cool! Add in merchant id also?

**Comment by robbieaverill** [comment]
@ScopeyNZ perhaps the issue-keys endpoint could return a bit more information to support this functionality? Otherwise we'd need to add another endpoint to the API to handle this

**Comment by ScopeyNZ** [comment]
> This is cool! Add in merchant id also?

Sounds good. When we have multi-merchant this might need some thinking - but if we have an approach like the Contentful CLI, you can put the CLI into the context of a specific merchant (it's a "space" for the Contentful CLI).

> perhaps the issue-keys endpoint could return a bit more information to support this functionality

Sounds good to me.

**Comment by dvnkshl** [comment]
Could in theory use the /merchant endpoint for the data?

**Comment by robbieaverill** [comment]
@dvnkshl yeah good call. That'd cover the merchant info part, but if we're aiming to do multi user/merchant in future we should keep the user data separate. Perhaps we should add a new endpoint for this, since `issue-keys` should really just be issuing keys.

Perhaps something like `/v1/developer/user` which returns your user data? The existing endpoint is `/v1/developer/login/issue-keys`

**Comment by robbieaverill** [comment]
PRs for this are up
