### ISSUE TITLE
Group commands into sections

### ISSUE THREAD

**Issue by robbieaverill** [chec/cli#9]
```
COMMANDS
  help      display help for chec
  log       Get full detail about a given log ID
  login     Log into your Chec.io account
  logout    Log out of your account
  logs      Show a summary of your API requests processed by Chec.io
  register  Register an account with Chec.io
  request   Run abstract API request
```

I think we could group these. They represent auth commands, and then functional commands. That might be a good start?

**Comment by robbieaverill** [comment]
I can't see anything obvious in the oclif docs about doing this, so we may need to build a [plugin](https://oclif.io/docs/plugins) for oclif to make it work

**Comment by ScopeyNZ** [comment]
I like the idea. Not so much that we have to build a plugin for it 😅 .

**Comment by robbieaverill** [comment]
#wontfix
